version: "3"

services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: eating-habits-db
    volumes:
      - ./dbData:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eating-habits
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  php:
    image: snaksa/eating-habits-backend:mvp
    build:
      context: .
    container_name: eating-habits-backend-php
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
